# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6e773920bc8c9a7884626ede6531440e828b35e05ddffbddfb1d1d921a24ebb1c494f7ad89599d62b25c26f757a97edfed47493a64f2f67d8df99e0d0fdfa5e7

test:
  secret_key_base: c9662eec45697d11df6fffa5f51c97eda52576dd77a6f0c7abbd63da331fbfc32aa37e9883b4fd914c54626817ed18558260b0a7f213ccf3589c4c3c282dab92

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
